[package]
name = "bolt"
entry = "main.bend"

[deps.ezjson]
hash = "0x81c67699424929b5c44cd8577e18117f"
git = "https://github.com/Emerging-Patterns/ezjson"
rev = "f35ea6ce89962d338cdc0735cc7724ed82d47594"
tag = "v1.1.0"
root = "."
narHash = "sha256-yHxl1aW4luf2bdPqOUcULhOEZLlcaTOWjTrPJys4CMI="
entry = "main.bend"

[deps.snap]
hash = "0x103d0af04de36ab98b311e537366ec67"
git = "https://github.com/Emerging-Patterns/snap"
rev = "ced24e103db518e37f565c577ef312602c217cf5"
tag = "v1.0.0"
root = "."
narHash = "sha256-dEO94GFkcgssyzOqz4A5VveB3npPq4/zpDpI+EvqnvI="
entry = "main.bend"

[deps.shake]
hash = "0x085b03c84ca37125e38dddede7b91e55"
git = "https://github.com/Emerging-Patterns/shake"
rev = "ddb93921dea168aed7a37d3e56e00c4732cf9082"
tag = "v0.2.0"
root = "."
narHash = "sha256-o5NRUjz6OBNMecXY8CZzYQpqoGFxdolD/ST8rIgAnLo="
entry = "main.bend"
