[package]
name = "bolt"
entry = "main.bend"

[deps.shake]
hash = "0xba6940aab8a335b70bf79944bd9b53c4"
git = "https://github.com/Emerging-Patterns/shake"
rev = "cb02b47e80fdab81dbaa8c3cec2356f7a22d02b0"
tag = "v0.1.1"
root = "shake"
narHash = "sha256-G4uW2UV4Me6lJYxGU5rfn2kvJKs+/un4Hc0OjcirL7A="
entry = "shake/main.bend"

[deps.ezjson]
hash = "0xd9c8d4d2899ddda845dfa7525a3568ea"
git = "https://github.com/Emerging-Patterns/ezjson"
rev = "089d5206502e0670e04ce69b9a189948e89c0194"
tag = "v0.4.2"
root = "ezjson"
narHash = "sha256-I/vlCDPiZh77HwwtTsHNZTyMC6c4IBjhA3uasfc6h6E="
entry = "ezjson/main.bend"

[deps.snap]
hash = "0x9bfd9d57916f3439316c2775fd1f10b4"
git = "https://github.com/Emerging-Patterns/snap"
rev = "9c2aee9f139c353201ca3b086b15703ca7c63e30"
tag = "v0.1.0"
root = "snap"
narHash = "sha256-0paitFZb+gr17vw3JbvKoEDGHyRF5I+Y7SvdY1Y7IjU="
entry = "snap/main.bend"
