#!/usr/bin/env bash
# generate <dir>/.gate/all.bend: every tests/*.bend of <dir> in one binary
# usage: agg.sh <dir> [--js]   (--js leaves out the `# lanes: native` tests)
set -eu
dir=$1; js=${2:-}
mkdir -p "$dir/.gate"
f=$dir/.gate/all${js:+.js}.bend
ts=()
for t in "$dir"/tests/*.bend; do
  [ -f "$t" ] || continue
  [ -n "$js" ] && grep -q '^# lanes: native' "$t" && continue
  ts+=("$t")
done
{
  echo "# generated by gate.sh: every test of $dir in one binary. bend has no"
  echo "# incremental compile, so each native build pays for the whole import"
  echo "# closure, and these tests' closures are nearly the same set."
  echo "import Base"
  i=0; for t in "${ts[@]}"; do i=$((i+1)); echo "import ../tests/$(basename "$t") as T$i"; done
  echo
  echo "def main() -> IO(Unit):"
  echo "  do IO<Unit>:"
  i=0; for t in "${ts[@]}"; do i=$((i+1))
    echo "    IO.print(\"@@gate@@ $t\")"
    echo "    T$i.main()"
  done
} > "$f"
printf '%s\n' "$f"
